### PR TITLE
Protstab v2

### PR DESCRIPTION
**Pull request by danbryce**
Running example/protstab.py will generate a new plan!  It needs xplan protstab-v2 branch.

### CODE REVIEW

**Comment by mwes** [comment]
Seeing a pyDOE error (module not found). Does this have https://github.com/SD2E/xplan_api/pull/21?

**Comment by danbryce** [comment]
I’ve seen the same thing.  I am able to run the setup script again and it works.  I believe its due to cloning the pyDOE branch every time as part of the setup.  We really aught to keep a local cache.

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
OK, I'll retest and test locally as well.

**Comment by danbryce** [comment]
Seems to work on my side.

**Comment by mwes** [comment]
Is this calling xplan now? The integration test can support this, but I don't think the built-in unit tests support this. Can we separate the tests?
```
Traceback (most recent call last):
  File "/jenkins/home/workspace/xplan_api tests/tests/ProtStab/../../example/protstab.py", line 134, in <module>
    xp = xplan.XPlan()
  File "/jenkins/home/shiningpanda/jobs/39cbb57b/virtualenvs/d41d8cd9/lib/python3.6/site-packages/xplan_api/xplan.py", line 52, in __init__
    self.xplan_path
xplan_api.xplan.XPlanPathInvalid: Provided XPlan path -- None --is not valid. Provide a valid path or set the XPLAN_PATH environment variable
```

**Comment by danbryce** [comment]
Yes.  I added this as a convenience for the labs running the scripts.  The yeast gates and protstab scripts will invoke xplan.  It assumes that you either run ./get-xplan.sh or set XPLAN_PATH to the right location.  

The problem is that we have protstab on a branch because we haven’t yet streamlined the entrypoint to xplan.  For now, develop will only work for yeast gates.  Otherwise you need protstab-V2 for both xplan_api and xplan.  I hope to get this cleaned up and merge protstab-v2 into develop today.

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
retest this please

**Comment by mdehavensift** [comment]
@mwes @danbryce This might be related to me changing the jenkins job to use python3. I updated the setup.py script to pull the pyDOE fork which works for python3. Rebasing this to include the changes to setup.py from last night might get this to work again. I'll check on my side.

**Comment by mwes** [comment]
Thanks Matt. It looks like it's installing correctly now, currently working on the xplan dependencies.

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
OK I have this running xplan now. Does it need the same branch? 
```
resources['plasmids']: Do not have data for experiment_set: protstab-Q2
resources['hosts']: Do not have data for experiment_set: protstab-Q2
resources['blank_colonies']: Do not have data for experiment_set: protstab-Q2
resources['colonies']: Do not have data for experiment_set: protstab-Q2
resources['media']: Do not have data for experiment_set: protstab-Q2
resources['bead_colonies']: Do not have data for experiment_set: protstab-Q2
resources['inducers']: Do not have data for experiment_set: protstab-Q2
Traceback (most recent call last):
  File "/jenkins/home/workspace/xplan_api tests/tests/ProtStab/../../example/protstab.py", line 135, in <module>
    xp.run_xplan(str(p),json_output_path=plan_out)
  File "/jenkins/home/workspace/xplan_api tests/xplan_api/xplan.py", line 87, in run_xplan
    res = self.run_xplan_problem_file(path, json_output_path=json_output_path)
  File "/jenkins/home/workspace/xplan_api tests/xplan_api/xplan.py", line 108, in run_xplan_problem_file
    cmd=cmd_list, ec=exit_code, so=out, se=err
xplan_api.xplan.XPlanFailed: ['sbcl', '--script', 'run-xplan-new.lisp', '/tmp/tmpkdj20_be'] failed with exit code 1
b'\n\nSHOP2 version 2.11.0\nCopyright (C) 2002  University of Maryland.\nModifications by SIFT, LLC personnel Copyright (C) 2004-2016 SIFT, LLC.\nThis software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY\nKIND, either express or implied.  This software is distributed under an\nMPL/GPL/LGPL triple license.  For details, see the software source file.\n; compiling file "/jenkins/home/workspace/xplan_api tests/xplan/xplan/code/exp-design-models/xpu-package.lisp" (written 29 MAR 2018 03:53:57 PM):\n; compiling (IN-PACKAGE :COMMON-LISP-USER)\n; compiling (DEFPACKAGE :XPLAN-USER ...)\n\n; /var/lib/jenkins/.cache/common-lisp/sbcl-1.4.0-1.el7-linux-x64/jenkins/home/workspace/xplan_api tests/xplan/xplan/code/exp-design-models/xpu-package-TMP.fasl written\n; compilation finished in 0:00:00.001\n; compiling file "/jenkins/home/workspace/xplan_api tests/xplan/xplan/code/exp-design-models/xpu-defns.lisp" (written 29 MAR 2018 03:53:57 PM):\n; compiling (IN-PACKAGE :XP-USER)\n\n; /var/lib/jenkins/.cache/common-lisp/sbcl-1.4.0-1.el7-linux-x64/jenkins/home/workspace/xplan_api tests/xplan/xplan/code/exp-design-models/xpu-defns-TMP.fasl written\n; compilation finished in 0:00:00.000\n; compiling file "/jenkins/home/workspace/xplan_api tests/xplan/xplan/code/exp-design-models/xplan-user.lisp" (written 29 MAR 2018 03:53:57 PM):\n; compiling (IN-PACKAGE :XPU)\n\n; /var/lib/jenkins/.cache/common-lisp/sbcl-1.4.0-1.el7-linux-x64/jenkins/home/workspace/xplan_api tests/xplan/xplan/code/exp-design-models/xplan-user-TMP.fasl written\n; compilation finished in 0:00:00.001\nStarting XPLAN prototype...\n\nDefining domain YEAST-GATES...\n\nDefining problem TEST ...\n\nCalling SHOP2...\n'
b'Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING\n                                    {1001952A53}>:\n  No domain named PROTSTAB\n\nBacktrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001952A53}>\n0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "No domain named ~A" {1001F12463}> #<unused argument>)\n1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "No domain named ~A" {1001F12463}>)\n2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "No domain named ~A" {1001F12463}>)\n3: (ERROR "No domain named ~A" PROTSTAB)\n4: (FIND-DOMAIN PROTSTAB :ERROR)\n5: (FIND-PLANS TEST :DOMAIN NIL :WHICH :FIRST :VERBOSE :PLANS :GC NIL :PP NIL :PLAN-TREE NIL :OPTIMIZE-COST NIL :COLLECT-STATE NIL :TIME-LIMIT NIL :EXPLANATION NIL :DEPTH-CUTOFF NIL :STATE #<unused argument> :STATE-TYPE NIL :HAND-STEER NIL :LEASHED NIL)\n6: (FIND-EXPERIMENT-WORKFLOW TEST :ID NIL :PLAN-NAME NIL :EXPERIMENT-SET NIL :EXPERIMENT-ID NIL :EXPERIMENT-LAB NIL :DOMAIN-FILE "exp-design-models/yeastgates-with-costs/yeast-gates.lisp" :PROBLEM-FILE "/tmp/tmpkdj20_be" :PLANS-OUTFILE NIL :JSON-OUTFILE NIL :AUTOPROTOCOL-OUTFILE NIL :PLAN-TREE NIL :WHICH :FIRST :VERBOSE :PLANS :XPLAN-PPRINT NIL)\n7: (SB-INT:SIMPLE-EVAL-IN-LEXENV (FIND-EXPERIMENT-WORKFLOW (QUOTE TEST) :DOMAIN-FILE "exp-design-models/yeastgates-with-costs/yeast-gates.lisp" :PROBLEM-FILE (FIRST (UIOP/IMAGE:COMMAND-LINE-ARGUMENTS)) :WHICH :FIRST :VERBOSE :PLANS :PLAN-TREE NIL ...) #<NULL-LEXENV>)\n8: (SB-EXT:EVAL-TLF (FIND-EXPERIMENT-WORKFLOW (QUOTE TEST) :DOMAIN-FILE "exp-design-models/yeastgates-with-costs/yeast-gates.lisp" :PROBLEM-FILE (FIRST (UIOP/IMAGE:COMMAND-LINE-ARGUMENTS)) :WHICH :FIRST :VERBOSE :PLANS :PLAN-TREE NIL ...) 7 NIL)\n9: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (FIND-EXPERIMENT-WORKFLOW (QUOTE TEST) :DOMAIN-FILE "exp-design-models/yeastgates-with-costs/yeast-gates.lisp" :PROBLEM-FILE (FIRST (UIOP/IMAGE:COMMAND-LINE-ARGUMENTS)) :WHICH :FIRST :VERBOSE :PLANS :PLAN-TREE NIL ...) 7)\n10: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (FIND-EXPERIMENT-WORKFLOW (QUOTE TEST) :DOMAIN-FILE "exp-design-models/yeastgates-with-costs/yeast-gates.lisp" :PROBLEM-FILE (FIRST (UIOP/IMAGE:COMMAND-LINE-ARGUMENTS)) :WHICH :FIRST :VERBOSE :PLANS :PLAN-TREE NIL ...) :CURRENT-INDEX 7)\n11: (SB-C::%DO-FORMS-FROM-INFO #<CLOSURE (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {100195AA7B}> #<SB-C::SOURCE-INFO {100195AA33}> SB-C::INPUT-ERROR-IN-LOAD)\n12: (SB-INT:LOAD-AS-SOURCE #<SB-SYS:FD-STREAM for "file /jenkins/home/workspace/xplan_api tests/xplan/xplan/code/run-xplan-new.lisp" {10019499C3}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")\n13: ((FLET SB-FASL::THUNK :IN LOAD))\n14: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN LOAD) {7FFFF09676BB}> #<SB-SYS:FD-STREAM for "file /jenkins/home/workspace/xplan_api tests/xplan/xplan/code/run-xplan-new.lisp" {10019499C3}>)\n15: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<SB-SYS:FD-STREAM for "file /jenkins/home/workspace/xplan_api tests/xplan/xplan/code/run-xplan-new.lisp" {10019499C3}> NIL)\n16: (LOAD #<SB-SYS:FD-STREAM for "file /jenkins/home/workspace/xplan_api tests/xplan/xplan/code/run-xplan-new.lisp" {10019499C3}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)\n17: ((FLET SB-IMPL::LOAD-SCRIPT :IN SB-IMPL::PROCESS-SCRIPT) #<SB-SYS:FD-STREAM for "file /jenkins/home/workspace/xplan_api tests/xplan/xplan/code/run-xplan-new.lisp" {10019499C3}>)\n18: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::PROCESS-SCRIPT))\n19: (SB-IMPL::PROCESS-SCRIPT "run-xplan-new.lisp")\n20: (SB-IMPL::TOPLEVEL-INIT)\n21: ((FLET "WITHOUT-INTERRUPTS-BODY-35" :IN SB-EXT:SAVE-LISP-AND-DIE))\n22: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))\n\nunhandled condition in --disable-debugger mode, quitting\n'
====================== 1 failed, 9 passed in 8.48 seconds ======================
```

**Comment by mdehavensift** [comment]
I believe xplan needs to be on the same branch, protstab-v2, at the moment.

**Comment by mwes** [comment]
retest this please

**Comment by mwes** [comment]
retest this please

**Pull request merged**
