### PR TITLE
Stub protstab

### PR DESCRIPTION
**Pull request by danbryce**
Additions to support protein stability.

### CODE REVIEW

**Comment by mwes** [comment]
Can one of the admins verify this patch?

**Comment by danbryce** [comment]
add to whitelist danbryce

**Comment by mdehavensift** [comment]
retest this please

**Comment by mdehavensift** [comment]
retest this please

**Comment by mdehavensift** [comment]
retest this please

**Comment by mwes** [comment]
@mdehavensift Can you check the Jenkins job configuration? We want to configure it to test the PR branch using: ${sha1}
image

**Comment by mwes** [comment]
Also, set the refspec to `+refs/pull/*:refs/remotes/origin/pr/*` per: https://github.com/janinko/ghprb#creating-a-job

**Comment by mdehavensift** [comment]
@mwes Fixed those two issues. Seems to be working now. Thanks.

**Comment by mdehavensift** [comment]
retest this please

**Pull request merged**
