### PR TITLE
Raise and catch specific exception when a resource is not available f…

### PR DESCRIPTION
**Pull request by mdehavensift**
…or an experiment set.

When raising and catching Exception, every possible error gets caught in the except block. This allows any error the be recovered from when getting resources, which may not be desirable. It makes it a bit harder to recognize when there is an unexpected error occurring, because everything just continues on.

Using a new exception, get_experiment_resources will only recover from an error where a specified resources has not been defined. Any other error will cause a crash and needs to be fixed.

Also puts some of the repeated code in a helper function.

### CODE REVIEW

**Comment by danbryce** [comment]
@mdehavensift develop is passing tests but this is not even after rebasing.  Can you have a look?

**Comment by mdehavensift** [comment]
Fixed an issue related to the rule 30 plasmid query. A new issue has appeared related to the move to python3. Working on this issue now.

**Comment by mdehavensift** [comment]
retest this please

**Comment by mdehavensift** [comment]
Changed jenkins job to use python3. Updated setup script to install the forked version of pydoe that works on python3.

@danbryce tests are passing now.

**Pull request merged**
