### PR TITLE
Streamline s expr class

### PR DESCRIPTION
**Pull request by mdehavensift**
Implicit data requirements make it hard to refactor existing examples and create new ones. Currently requires looking at code to try to decipher what is required. This branch adds schemas that validate the input and give a person defining an experiment a place to look to find out how the input should be formatted.

### CODE REVIEW

**Comment by mwes** [comment]
Can one of the admins verify this patch?

**Comment by danbryce** [comment]
Tests pass for me.

**Comment by mdehavensift** [comment]
Will wait for #8 to merge into master as they will conflict. I don't think it will be too bad, though.

**Comment by danbryce** [comment]
#8 is merged!

**Comment by mdehavensift** [comment]
Rebased with master after #6 merged. Added commit to resolve new conflicts. Only a few lines needed to change.
Tests still pass

**Pull request merged**
